### DISCUSSION TITLE
Help with setting and etc.

### DISCUSSION THREAD

**Discussion by Akenjeru** [ImLovinIt/Nightscout-SisensingCGM-Uploader#3] [Q&A] [answered]
Hello, thank you for this guide. I have installed the Chinese application Sisensing (SiBionics) and registered with a Chinese number. The sensors are still on their way to me, so I have a couple of questions. I have installed the PCAPdroid app on Android. Where can I find the Authorization: Bearer? Or is it not available until I set up the sensor? Also, since I will be installing this on my Ubuntu virtual machine, could I ask you for a Docker Compose file with all the variables? I'm not very good at creating Docker Compose files, but I can install it and replace the necessary details. The sensors are on their way, and I would like to transmit my child's blood sugar data there.
I created a docker-compose.yml file. Can you check if I did it correctly?

```
version: '3'

services:
  nightscout-uploader:
    image: imlovinit1019/nightscout-sisensingcgm-uploader:latest
    container_name: nightscout-uploader
    volumes:
      - ./config:/app/config
    environment:
      ss_token: abcdefgh-1234-ijkl-5678-mnopqrstuvwx
      ss_region: CN
      ns_url: https://nightscout.azurewebsites.net/
      ns_api_secret: 162f14de46149447c3338a8286223de407e3b2fa
      uploader_interval: 5
      uploader_max_entries: 0
      uploader_all_data: false


volumes:
  nightscout:
```
